### ISSUE TITLE
Alloy Compile Error

### ISSUE THREAD

**Issue by tenam24** [juanagu/com.juanagu.takepicture#1]
Hi Juan,

After installing your widget via gittio. I am getting Alloy compile error. I check the widget.json file and there's no modules. Is 'co.clarika.fab' missing? Could you please help me out. Thanks!

[INFO] [widget.xml] com.juanagu.takepicture view processing...
[INFO]   style:      "widget.tss"
[INFO]   view:       "widget.xml"
[ERROR] widget "co.clarika.fab" view "widget" does not exist.
[ERROR] The following paths were inspected:
[ERROR] Alloy Compile Error

**Comment by juanagu** [comment]
Install https://github.com/juanagu/TiFab 
Fix in v2.0
